routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('entrega.index');
});

Route::resource('entrega', 'EntregaController')->middleware(['web', 'auth']);

Route::auth();

Auth::routes();

app/Entrega.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entrega extends Model
{
    protected $fillable = [
        'cliente_nome',
        'data_entrega',
        'partida',
        'destino',
        'user_id',
    ];

    protected $dates = ['data_entrega'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EntregaController.php
<?php

namespace App\Http\Controllers;

use App\Entrega;
use App\Http\Requests\EntregaRequest;
use Illuminate\Http\Request;

class EntregaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dados = Entrega::all();
        return view('entregas-index', compact('dados'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('entregas-form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  EntregaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EntregaRequest $request)
    {
        $request->merge(['user_id'=>auth()->user()->getKey()]); // ADICIONANDO ID DO USUÁRIO LOGADO
        Entrega::create($request->all());
        return redirect()->route('entrega.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Entrega  $entrega
     * @return \Illuminate\Http\Response
     */
    public function show(Entrega $entrega)
    {
        return view('mapa', compact('entrega'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/entregas-form.blade.php
@extends('layouts.template')

@section('content')
    {!! Form::open(['route'=>'entrega.store']) !!}
    <div class="form-group">
        <label>Nome</label>
        {!! Form::text('cliente_nome', null, ['class'=>'form-control form-control-sm'.($errors->has('cliente_nome') ?
        ' is-invalid' : ''), 'placeholder'=>'Informe seu nome completo']) !!}

        @if ($errors->has('cliente_nome'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('cliente_nome') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group">
        <label>Data entrega</label>
        {!! Form::date('data_entrega', null, ['class'=>'form-control form-control-sm'.($errors->has('data_entrega') ?
        ' is-invalid' : '')]) !!}

        @if ($errors->has('data_entrega'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('data_entrega') }}</strong>
            </span>
        @endif
    </div>
    <div class="row">
        <div class="col-sm">
            <div class="form-group">
                <label>Partida</label>
                {!! Form::text('partida', null, ['class'=>'form-control form-control-sm'.($errors->has('partida') ?
                ' is-invalid' : ''), 'id'=>'autocomplete']) !!}

                @if ($errors->has('partida'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('partida') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="col-sm">
            <div class="form-group">
                <label>Chegada</label>
                {!! Form::text('destino', null, ['class'=>'form-control form-control-sm'.($errors->has('partida') ?
                ' is-invalid' : ''), 'id'=>'autocomplete2']) !!}

                @if ($errors->has('destino'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('destino') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-sm btn-primary">Salvar</button>
    <a class="btn btn-sm btn-danger" href="{{route('entrega.index')}}">Cancelar</a>
    {!! Form::close() !!}
@endsection

resources/views/entregas-index.blade.php
@extends('layouts.template')

@section('content')
    <a class="btn btn-sm btn-primary" href="{{route('entrega.create')}}">Nova entrega</a>
    <br>
    <br>

    <table class="table table-bordered table-striped table-hover table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th>Cliente</th>
            <th>Data entrega</th>
            <th>Partida</th>
            <th>Destino</th>
            <th>Mapa</th>
        </tr>
        </thead>

        <tbody>
        @forelse($dados as $d)
            <tr>
                <td>{{$d->getKey()}}</td>
                <td>{{$d->cliente_nome}}</td>
                <td>{{$d->data_entrega->format('d/m/Y')}}</td>
                <td>{{$d->partida}}</td>
                <td>{{$d->destino}}</td>
                <td>
                    <a href="{{{route('entrega.show', $d->getKey())}}}">Mapa</a>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="6">Não há dados!</td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection

resources/views/layouts/template.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Criar usuário') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <hr>

        <main class="container-fluid">
            @yield('content')
        </main>
    </div>

    <script src="{{ mix('js/app.js') }}"></script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3_c2_0GED4sMbgc5rLSe-iACKpA3fHhM&libraries=places&callback=escolheFuncao"
            type="text/javascript"></script>
</body>
</html>

resources/views/mapa.blade.php
@extends('layouts.template')

@section('content')
    <div id="floating-panel">
        <a href="{{route('entrega.index')}}" class="btn btn-primary">Voltar</a>
        <br>
        <br>
        <p><strong>#</strong>{{$entrega->getKey()}} - <strong>Cliente: </strong>{{$entrega->cliente_nome}} - <strong>Data: </strong>{{$entrega->data_entrega->format('d/m/Y')}}</p>
        <p>"{{$entrega->partida}}" <strong>-></strong> "{{$entrega->destino}}"</p>

        <input type="hidden" id="start" value="{{$entrega->partida}}">
        <input type="hidden" id="end" value="{{$entrega->destino}}">

        <div id="map"></div>
    </div>
@endsection